//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System_Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketID { get; set; }
        public string owner { get; set; }
        public string storeNumb { get; set; }
        public string deviceNumber { get; set; }
        public string team { get; set; }
        public string status { get; set; }
        public string severity { get; set; }
        public string priority { get; set; }
        public string type { get; set; }
        public string tCode { get; set; }
        public string tSubtype { get; set; }
        public string tCategory { get; set; }
        public string tType { get; set; }
        public string problemNotes { get; set; }
        public string callerPhone { get; set; }
        public string callerName { get; set; }
        public string resCode { get; set; }
        public string resType { get; set; }
        public string resNotes { get; set; }
        public string created { get; set; }
        public string closed { get; set; }
        public string lastUpdatedBy { get; set; }
        public string assigned { get; set; }
    }
}
